BEGIN;
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('ResearchLife92', 'cf47f8a634444b6b620b3318396131e7', 1998, 11, 26, "PhD candidate in South Asian Studies. L'Orientale University of Naples, Italy. Sufi premākhyāns, literature, language enthusiast. Hindi/Urdu/Farsi/Sanskrit");
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('stephenniem', 'cf47f8a634444b6b620b3318396131e7', 1996, 04, 21, 'Prof Islamic art @UTAustin, President of @MideastMedieval, Syria, archaeology & heritage, author of THE CITIZEN KANE OF ISLAM-CENTRIC CAT-THEMED TWITTER THREADS');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('RebeccaSpang', 'cf47f8a634444b6b620b3318396131e7', 1999, 12, 26, 'historian of money, revolutions, restaurants; 18C Studies; Professor @IUBloomington @iubhistory @IULAMP; formerly @YaleICF @YaleSOM @UCLHistory;');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('mariamsabri', 'cf47f8a634444b6b620b3318396131e7', 1997, 03, 14, 'PhD student @UCBHistory. #SouthAsia | #MughalIndia | #BritishEmpire | #STS |#EarlyModernScience | #IslamicStudies | #Twitterstorians | #WomenAlsoKnowHistory');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('shamshiadad', 'cf47f8a634444b6b620b3318396131e7', 1998, 11, 26, "for a little time to be poor and wretched on the earth, and then to become earth itself");
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('ranazaher', 'cf47f8a634444b6b620b3318396131e7', 1996, 04, 21, 'Archaeologist, M.A. • Illustrator • Designer | specializing in Syro-Anatolian / Mesopotamian sculptural art and visual culture | American University of Beirut');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('BellaRaeAnne', 'cf47f8a634444b6b620b3318396131e7', 1999, 12, 26, 'M.A. in Classical Civilisations ☄️ Art commissions: OPEN ☄️ Founder & Creative Director for @GirlHQfdn ☄️');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('grantb97', 'cf47f8a634444b6b620b3318396131e7', 1997, 03, 14, 'Just a young man with big dreams Instagram: good_ole_grant ⬇');
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('BDSixsmith', 'cf47f8a634444b6b620b3318396131e7', 1998, 11, 26, "English writer in Poland. Contributor to @SpectatorUSA. Columnist for @arcdigi. My newsletter: https://bensixsmith.substack.com");
INSERT INTO `User` (UserID, Password, BirthYear, BirthMonth, BirthDay, Bio)  VALUES ('phl43', 'cf47f8a634444b6b620b3318396131e7', 1996, 04, 21, "I'm a PhD candidate in philosophy at Cornell, but I live in Paris now. I also have a blog where I write about stuff.");
COMMIT;

BEGIN;
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (1, 'text', 'Looking forward to reading this collection of provocations on the meanings and uses of the “vernacular” in #SouthAsia: https://www.tandfonline.com/doi/full/10.1080/02759527.2020.1725224', '', 'ResearchLife92', 2020, 04, 25, 19, 42, 50);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (2, 'text', 'Birth of #globalization? https://www.theguardian.com/science/2020/apr/18/mediterranean-shipwrecks-reveal-birth-of-globalisation-in-trade', '', 'stephenniem', 2020, 04, 22, 15, 42, 35);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (3, 'text', 'My college roommate is a talented, loving person; her life has largely been a tale of woe. Her husband was murdered in a hate crime. Her oldest brother is dying now in a nursing home on the opposite side of the country. It goes on. She has sewn 425 masks, given them away. #covid19', '', 'RebeccaSpang', 2020, 04, 25, 19, 59, 56);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (4, 'text', 'poori qaum ko Ralph Lauren ki taraf say dilli Ramazan Mubarak! #Ramadan', '', 'mariamsabri', 2020, 05, 22, 16, 42, 51);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (5, 'both', 'here’s a photo of a tiny book that I maniacally filled with every compound word used in #Ulysses when I was a teenager', 'https://pbs.twimg.com/media/EWZlQlvXkAALnep.jpg', 'shamshiadad', 2020, 04, 24, 14, 41, 54);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (6, 'text', 'The civil war in #Lebanon will end the day we can read about it in schools', '', 'ranazaher', 2020, 04, 13, 14, 53, 32);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (7, 'text', "Been thinking about the connections between the ways we talk about sex and dating, how it's used to measure someone's worth, and the ways it facilitates unhealthy and destructive #relationships.", '', 'BellaRaeAnne', 2020, 04, 25, 18, 51, 55);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (8, 'text', 'Take it easy and be safe out there #StaySafe', '', 'grantb97', 2020, 04, 24, 11, 59, 58);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (9, 'text', 'Firing AK-47s into the air to support the #NHS.', '', 'BDSixsmith', 2020, 04, 25, 19, 59, 56);
INSERT INTO `Post` (PostID, Type, Body, ImageURL, CreatedBy, YearCreated, MonthCreated, DayCreated, HourCreated, MinuteCreated, SecondCreated)  VALUES (10, 'text', "Un homme de 101 ans a survécu au COVID-19 après avoir déjà survécu à la grippe espagnole et à l'Holocauste. Lors d'une conférence de presse, le virus #Ebola a déclaré qu'il n'était pas question qu'il approche de ce type.", '', 'phl43', 2020, 04, 25, 11, 34, 21);
COMMIT;

BEGIN;
INSERT INTO `Topic` (TopicID)  VALUES ('#SouthAsia');
INSERT INTO `Topic` (TopicID)  VALUES ('#globalization');
INSERT INTO `Topic` (TopicID)  VALUES ('#covid19');
INSERT INTO `Topic` (TopicID)  VALUES ('#Ramadan');
INSERT INTO `Topic` (TopicID)  VALUES ('#Ulysses');
INSERT INTO `Topic` (TopicID)  VALUES ('#Lebanon');
INSERT INTO `Topic` (TopicID)  VALUES ('#relationships');
INSERT INTO `Topic` (TopicID)  VALUES ('#StaySafe');
INSERT INTO `Topic` (TopicID)  VALUES ('#NHS');
INSERT INTO `Topic` (TopicID)  VALUES ('#Ebola');
COMMIT;

BEGIN;
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (1, '#SouthAsia');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (2, '#globalization');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (3, '#covid19');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (4, '#Ramadan');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (5, '#Ulysses');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (6, '#Lebanon');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (7, '#relationships');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (8, '#StaySafe');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (9, '#NHS');
INSERT INTO `PostTopic` (PostID, TopicID)  VALUES (10, '#Ebola');
COMMIT;